name: Web CI&CD

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'web build & deploy')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build cmd/main.go;

#      - name: Install golangci-lint
#        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2

#     - name: Run golangci-lint
#        run: golangci-lint run

      #- name: Run tests
      #  run: go test -cover ./... -coverprofile=profile; go tool cover -func profile

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: server
          path: web

  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Download bin file
         uses: actions/download-artifact@v1
         with:
           name: server

       - name: Transfer bin file to server
         uses: appleboy/scp-action@v0.1.4
         with:
           host: 62.84.99.143
           username: ubuntu
           key: ${{ secrets.WEB_PRIVATE_KEY }}
           source: "server"
           target: "/home/ubuntu"

       - name: chmod
         uses: appleboy/ssh-action@master
         with:
           host: 62.84.99.143
           username: ubuntu
           key: ${{ secrets.WEB_PRIVATE_KEY }}
           script: |
             chmod 755 /home/ubuntu/server/run.sh
             chmod 755 /home/ubuntu/server/stop.sh

       - name: screen and restart server
         uses: appleboy/ssh-action@master
         with:
           host: 62.84.99.143
           username: ubuntu
           key: ${{ secrets.WEB_PRIVATE_KEY }}
           script: |
             PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin"
             cd /home/ubuntu/server
             nohup ./stop.sh > /dev/null 2>&1&
             nohup ./run.sh > logs.log 2>logs.log&
